PRAGMA foreign_keys = ON;

-- 목적: 최소 컬럼만으로도 관계 테이블을 만들 수 있음을 체감
DROP TABLE IF EXISTS orderitems;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS stores;
DROP TABLE IF EXISTS users;

CREATE TABLE users (Id TEXT PRIMARY KEY, Name TEXT NOT NULL);
CREATE TABLE stores (Id TEXT PRIMARY KEY, Name TEXT NOT NULL);
CREATE TABLE items (Id TEXT PRIMARY KEY, Name TEXT NOT NULL, UnitPrice INTEGER NOT NULL);

CREATE TABLE orders (
  Id TEXT PRIMARY KEY,
  OrderAt TEXT NOT NULL,
  StoreId TEXT NOT NULL,
  UserId TEXT NOT NULL,
  FOREIGN KEY(StoreId) REFERENCES stores(Id),
  FOREIGN KEY(UserId)  REFERENCES users(Id)
);

CREATE TABLE orderitems (
  Id TEXT PRIMARY KEY,
  OrderId TEXT NOT NULL,
  ItemId TEXT NOT NULL,
  Qty INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY(OrderId) REFERENCES orders(Id),
  FOREIGN KEY(ItemId)  REFERENCES items(Id)
);
